#!/usr/bin/env python3
"""Regenerate the self-hosted CJK font subsets from the localized content.

Folded into the build: tools/build-i18n.mjs runs this before it emits pages,
so the fonts always cover exactly the characters in use. It can also be run on
its own:  python3 tools/subset-cjk.py

Prerequisites:
  pip install fonttools brotli --break-system-packages
  npm install            (pulls the @fontsource source fonts listed below)

For each handled language it collects every CJK glyph used across that
language's body files plus the nav and meta strings, subsets and merges the
@fontsource source down to those glyphs (one small woff2 per weight), and
rewrites the language's font CSS. Latin text stays Mulish; only CJK glyphs use
the subset face.
"""
import glob, os, json, hashlib, tempfile, sys
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options
from fontTools.merge import Merger

ROOT = os.getcwd()
CFG = json.load(open('i18n/config.json', encoding='utf-8'))
# Where the @fontsource packages live. Defaults to the project node_modules;
# override with FONTSOURCE_DIR for a vendored or temp install.
FS_DIR = os.environ.get('FONTSOURCE_DIR', 'node_modules')

# Languages with a self-hosted CJK face. Add zh-Hant (noto-sans-tc) and
# th (noto-sans-thai) here when those locales go live.
FONTS = {
    'zh-Hans': dict(pkg='@fontsource/noto-sans-sc', family='Noto Sans SC',
                    weights=[400, 700], outdir='assets/fonts/noto',
                    prefix='noto-sans-sc', css='assets/fonts/noto/noto-sans-sc.css'),
}


def collect_glyphs(code):
    text = ''
    for f in glob.glob(f'i18n/bodies/*.{code}.html'):
        text += open(f, encoding='utf-8').read()
    nav = CFG['nav']
    for k in nav['labels']:
        text += nav['labels'][k].get(code, '')
    text += nav['languageLabel'].get(code, '') + nav['skip'].get(code, '')
    for page in CFG['pages'].values():
        for field in page.get('meta', {}).values():
            if isinstance(field, dict):
                text += field.get(code, '')

    def keep(ch):
        o = ord(ch)
        return (0x2014 <= o <= 0x2026) or (0x3000 <= o <= 0x9FFF) or (0xFF00 <= o <= 0xFFEF)
    return sorted(set(ch for ch in text if keep(ch)))


def _opts(names):
    o = Options()
    o.layout_features = []
    o.name_IDs = []
    o.notdef_outline = True
    o.glyph_names = names
    o.recalc_timestamp = False
    o.drop_tables += ['GSUB', 'GPOS', 'GDEF', 'FFTM']
    return o


def subset_weight(pkgdir, prefix, weight, unicodes, outdir):
    files = sorted(glob.glob(f'{pkgdir}/files/*-{weight}-normal.woff2'))
    tmp = tempfile.mkdtemp()
    pieces = []
    for f in files:
        font = TTFont(f)
        cmap = font.getBestCmap()
        have = [u for u in unicodes if u in cmap]
        if not have:
            font.close(); continue
        ss = Subsetter(options=_opts(True))
        ss.populate(unicodes=have); ss.subset(font)
        out = os.path.join(tmp, os.path.basename(f) + '.ttf')
        font.flavor = None; font.save(out); pieces.append(out); font.close()
    if not pieces:
        return None
    merged = TTFont(pieces[0]) if len(pieces) == 1 else Merger().merge(pieces)
    ss = Subsetter(options=_opts(False))
    ss.populate(unicodes=unicodes); ss.subset(merged)
    merged.flavor = 'woff2'
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, f'{prefix}-{weight}.woff2')
    merged.save(path)
    return path


def write_css(fc, faces, version):
    lines = ['/* Auto-generated by tools/subset-cjk.py. Subset to the glyphs used',
             '   on the localized pages and merged per weight. Do not edit by hand. */']
    for weight, rel in faces:
        lines += ['@font-face {',
                  f"  font-family: '{fc['family']}';",
                  '  font-style: normal;',
                  f'  font-weight: {weight};',
                  '  font-display: swap;',
                  f"  src: url('{rel}?v={version}') format('woff2');",
                  '}']
    lines += ['',
              '/* Append the CJK face to the type tokens. Loaded after the page',
              '   stylesheets so this redefinition wins the cascade. */',
              ':root {',
              f"  --sans:  'Mulish', '{fc['family']}', 'Helvetica Neue', Arial, sans-serif;",
              f"  --serif: 'Mulish', '{fc['family']}', 'Helvetica Neue', Arial, sans-serif;",
              '}', '']
    open(fc['css'], 'w', encoding='utf-8').write('\n'.join(lines))


def main():
    any_done = False
    for code, fc in FONTS.items():
        pkgdir = os.path.join(FS_DIR, *fc['pkg'].split('/'))
        if not os.path.isdir(pkgdir):
            print(f'[subset] skip {code}: {fc["pkg"]} not found in {FS_DIR} (run npm install)')
            continue
        glyphs = collect_glyphs(code)
        if not glyphs:
            print(f'[subset] skip {code}: no glyphs found')
            continue
        unicodes = [ord(c) for c in glyphs]
        version = hashlib.sha256(''.join(glyphs).encode('utf-8')).hexdigest()[:8]
        faces = []
        for w in fc['weights']:
            p = subset_weight(pkgdir, fc['prefix'], w, unicodes, fc['outdir'])
            rel = '/' + p.replace(os.sep, '/')
            faces.append((w, rel))
            print(f'[subset] {code} {w}: {os.path.getsize(p) // 1024} KB, {len(glyphs)} glyphs')
        write_css(fc, faces, version)
        print(f"[subset] {code} -> {fc['css']} (glyph version {version})")
        any_done = True
    if not any_done:
        print('[subset] nothing generated')


if __name__ == '__main__':
    main()
